title: FM Conference Deadlines # (Maintained by @mvcisback)
description: Countdowns to top CV/NLP/ML/Robotics/AI conference deadlines
author: Marcell Vazquez-Chanlatte

domain: "fmdeadlin.es"
baseurl: ""

twitter_username: mvcisback
twitter_hashtag: formalmethods
github_username: mvcisback
github_repo: fm-deadlines

markdown: kramdown
